player_limit: -1
ip_forward: true
permissions:
  default:
    - bungeecord.command.server
    - bungeecord.command.list
  admin:
    - bungeecord.command.alert
    - bungeecord.command.end
    - bungeecord.command.ip
    - bungeecord.command.reload
groups:
  md_5:
    - admin
timeout: 30000
log_commands: false
log_pings: true
network_compression_threshold: 256
online_mode: true
forge_support: false
disabled_commands:
  - disabledcommandhere
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25565
    restricted: false
listeners:
  - host: 0.0.0.0:25577
    motd: '&aA Minecraft Server'
    max_players: 1000
    priorities:
      - lobby
    bind_local_address: true
    ping_passthrough: false
    forced_hosts:
      pvp.md-5.net: pvp
    tab_list: GLOBAL_PING
    tab_size: 60
    query_port: 25577
    query_enabled: false
    proxy_protocol: false
    force_default_server: false
connection_throttle: 4000
connection_throttle_limit: 3
stats: replace-with-uuid
prevent_proxy_connections: false
remote_ping_cache: -1
forge_support: false
inject_commands: false
