default-logging: true
disable-world: false
disable-worlds:
  - world_disabled
mysql: false
mysql-host: 127.0.0.1
mysql-port: 3306
mysql-database: database
mysql-username: root
mysql-password: ''
table-prefix: 'co_'
use-mysql-feature-set: 0
language: en
api-enabled: true
check-updates: true
verbose: true
rollback-items: true
rollback-entities: true
skip-generic-data: true
network-debug: false
block-place: true
block-break: true
natural-break: true
block-movement: true
pickup: false
tnt-explosions: true
fire: true
lava: false
water-flow: false
liquid-tracking: true
sign-text: true
buckets: true
leaves-decay: true
tree-growth: true
mob-griefing: true
player-interactions: true
player-messages: true
player-commands: true
player-logins: true
player-deaths: true
inventory-changes: true
item-transactions: true
item-drops: true
item-pickups: true
zombie-villager-conversion: true
mushroom-block-bonemeal: true
auto-purge: 30
