checkforupdates: true
prevent-collision: true
use-new-deathmessages: false
suppress-conversion-warnings: false
nms-player-ticking: true
shield-blocking: true
no-delay-shield-blocking: false
show-shield-when-sword-in-hand: false
fix-1_8-direction: true
chunk-border-fix: false
minimize-cooldown: true
team-colour-fix: true
suppress-1_13-conversion-errors: false
unknown-entities-suppress-errors: false
serverside-piston-animation-patch: true
auto-team: true
quick-move-action-fix: false
hologram-y: -0.96
chat-ny-yes: false
truncate-1_14-books: false
left-handed-handling: true
fix-1_14-arrows: false
debug: false
bungee-ping-interval: 60
bungee-ping-save: true
bungee-servers: {}
block-protocols: []
block-versions: []
