bedrock:
  port: 19132
  clone-remote-port: false
  motd1: 'GeyserMC'
  motd2: 'Another Geyser server.'
  server-name: 'Geyser'
  compression-level: 6
  enable-proxy-protocol: false
remote:
  address: auto
  port: 25565
  auth-type: floodgate
  use-proxy-protocol: false
  forward-hostname: false
floodgate-key-file: key.pem
saved-user-logins: []
pending-authentication-timeout: 120
command-suggestions: true
passthrough-motd: false
passthrough-player-counts: false
legacy-ping-passthrough: false
ping-passthrough-interval: 3
forward-player-ping: false
max-players: 100
debug-mode: false
allow-third-party-capes: true
allow-third-party-ears: false
show-cooldown: title
show-coordinates: true
disable-bedrock-scaffolding: false
emote-offhand-workaround: 'disabled'
default-locale: en_us
cache-images: 0
allow-custom-skulls: true
add-non-bedrock-items: true
above-bedrock-nether-building: false
force-resource-packs: true
xbox-achievements-enabled: false
log-player-ip-addresses: true
notify-on-server-form-image-error: true
metrics:
  enabled: true
  uuid: generateduuid
config-version: 4
